### ISSUE TITLE
(Request) Spawn animals and plants

### ISSUE THREAD

**Issue by rasleraketer** [YimMenu/HorseMenu#101]
The option to make animals appear, alive, dead or paralyzed, would also be great. And the same with plants.

**Comment by Rxann** [comment]
Animal spawning is already a thing. animal models are in the ped spawner.

**Comment by bunnybuddy213** [comment]
Have the choice to spawn them alive dead and paralyzed can help a lot and and sort peds by category

**Comment by Rxann** [comment]
> Have the choice to spawn them alive dead and paralyzed can help a lot and and sort peds by category

#102 allows peds to be paralyzed of sorts.

**Comment by bunnybuddy213** [comment]
> > Have the choice to spawn them alive dead and paralyzed can help a lot and and sort peds by category
> 
> #102 allows peds to be paralyzed of sorts.

can we take samples from it?

**Comment by Rxann** [comment]
> > > Have the choice to spawn them alive dead and paralyzed can help a lot and and sort peds by category
> > 
> > 
> > #102 allows peds to be paralyzed of sorts.
> 
> can we take samples from it? and spawn dead for perfect skin

Just use the correct weapon to kill it and you have a perfect pelt. and if it is paralyzed it will not attack you.

**Comment by bunnybuddy213** [comment]
> > > > Have the choice to spawn them alive dead and paralyzed can help a lot and and sort peds by category
> > > 
> > > 
> > > #102 allows peds to be paralyzed of sorts.
> > 
> > 
> > can we take samples from it? and spawn dead for perfect skin
> 
> Just use the correct weapon to kill it and you have a perfect pelt. and if it is paralyzed it will not attack you.

Too complicated.. A menu mod is meant to make life easier 😁

**Comment by Rxann** [comment]
> Sorry I don't see this option

In the newest release, it is under Ped Spawner in the Self tab.

**Comment by Rxann** [comment]
> > > > > > Tener la opción de generarlos vivos, muertos y paralizados puede ayudar mucho y clasificar a los peds por categoría.
> > > > > 
> > > > > 
> > > > > #102 permite que los pediatras queden paralizados en cierto modo.
> > > > 
> > > > 
> > > > ¿Podemos tomar muestras de él? y engendra muertos para una piel perfecta
> > > 
> > > 
> > > Simplemente usa el arma correcta para matarlo y tendrás una piel perfecta. y si está paralizado no os atacará.
> > 
> > 
> > Demasiado complicado... Un mod de menú está destinado a hacer la vida más fácil 😁
> 
> They are still developing, they will surely improve it, but yes, I think I would put all the animals on a table, and next to them, only two buttons, one for them to appear dead and another for them to appear paralyzed.

It will most likely be a checkbox.

**Comment by rasleraketer** [comment]
> > Sorry I don't see this option
> 
> In the newest release, it is under Ped Spawner in the Self tab.

I dont see nothing, the last option is superjump and No clip, can you send me a images or something, thanks.

**Comment by bunnybuddy213** [comment]
> > > Sorry I don't see this option
> > 
> > 
> > In the newest release, it is under Ped Spawner in the Self tab.
> 
> I dont see nothing, the last option is superjump and No clip, can you send me a images or something, thanks.

Did you download the last dll from today ?

**Comment by rasleraketer** [comment]
> > > > Sorry I don't see this option
> > > 
> > > 
> > > In the newest release, it is under Ped Spawner in the Self tab.
> > 
> > 
> > I dont see nothing, the last option is superjump and No clip, can you send me a images or something, thanks.
> 
> Did you download the last dll from today ?
I donwloaded the version of yesterday

**Comment by Rxann** [comment]
> > > > > Sorry I don't see this option
> 
> > > > 
> 
> > > > 
> 
> > > > In the newest release, it is under Ped Spawner in the Self tab.
> 
> > > 
> 
> > > 
> 
> > > I dont see nothing, the last option is superjump and No clip, can you send me a images or something, thanks.
> 
> > 
> 
> > Did you download the last dll from today ?
> 
> I donwloaded the version of yesterday 
> 
> 

You need to have the one from today. the feature just got released in todays update

**Comment by rasleraketer** [comment]
> > > > > > Sorry I don't see this option
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > In the newest release, it is under Ped Spawner in the Self tab.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > I dont see nothing, the last option is superjump and No clip, can you send me a images or something, thanks.
> > 
> > 
> > > 
> > 
> > 
> > > Did you download the last dll from today ?
> > 
> > 
> > I donwloaded the version of yesterday
> 
> You need to have the one from today. the feature just got released in todays update

Yeah, i see the file, thanks!!!

**Comment by Rxann** [comment]
> > > > > > > Sorry I don't see this option
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > > > In the newest release, it is under Ped Spawner in the Self tab.
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > I dont see nothing, the last option is superjump and No clip, can you send me a images or something, thanks.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Did you download the last dll from today ?
> > > 
> > > 
> > > I donwloaded the version of yesterday
> > 
> > 
> > You need to have the one from today. the feature just got released in todays update
> 
> Yeah, i see the file, thanks!!!

Your welcome, if this is no longer an issue, you can close this.
