### ISSUE TITLE
[Request] Smart Teleport

### ISSUE THREAD

**Issue by bunnybuddy213** [YimMenu/HorseMenu#105]
Madam Nazar, Camp, distillery etc..

**Comment by Deadlineem** [comment]
This would have to use Blip teleportation i believe, thats how it works in GTA (unless you set coords manually to everything)

**Comment by Rxann** [comment]
> This would have to use Blip teleportation i believe, thats how it works in GTA (unless you set coords manually to everything)

i believe there are ways to get the cords of the premade blips. definitely a native thing

**Comment by bunnybuddy213** [comment]
> You'll need to use script globals, specifically to get the location of madam nazar. Look at the game scripts.

Hi tyackman, do you use discord bro?

**Comment by Rxann** [comment]
> > This would have to use Blip teleportation i believe, thats how it works in GTA (unless you set coords manually to everything)
> 
> 
> 
> Madam Nazar doesn't appear on the map until the player is close to her location so there won't be a blip to get the coords from. Think of it as Stash Houses, Street Dealers, Exotic Exports, Treasure Chests, etc... in GTA Online.
> 
> Take a look at ShinyWasabi's [Daily Collectibles](https://github.com/YimMenu-Lua/DailyCollectibles) and see how he's grabbing the coords for each collectible every day.
> 
> There is also a [web API](https://documenter.getpostman.com/view/6602370/SVtN3rnY) that could help.

We do have a http request feature already built in. Before I start building this I would like to know how @DayibBaba feels about this approach to implementation.

**Comment by DayibBaba** [comment]
We will not be needing any API's for such features. Ill personally have a look at the game scripts to get nazaars and other coordinates.

**Comment by Rxann** [comment]
> We will not be needing any API's for such features. Ill personally have a look at the game scripts to get nazaars and other coordinates.

Okay, let us know how it goes when you get a chance to do that. I can't seem to find anything when searching for nazar or madam in the scripts that seemed notable.
