### ISSUE TITLE
[Request] Pick Item Auto

### ISSUE THREAD

**Issue by bunnybuddy213** [YimMenu/HorseMenu#108]

**Comment by Rxann** [comment]
I tried to get this to work, using `TASK_PICKUP_CARRIABLE_ENTITY` but it didn't work.

**Comment by Deadlineem** [comment]
> I tried to get this to work, using `TASK_PICKUP_CARRIABLE_ENTITY` but it didn't work.

@Rxann 
Try using `ENTITY::_IS_ENTITY_FULLY_LOOTED(Entity entity)`

and if its false use `TASK::TASK_LOOT_ENTITY(Ped ped, Entity entity)` to loot it

then set it to looted afterwards using ENTITY::_SET_ENTITY_FULLY_LOOTED(Entity entity, Bool looted)

**Comment by Rxann** [comment]
> > I tried to get this to work, using `TASK_PICKUP_CARRIABLE_ENTITY` but it didn't work.
> 
> @Rxann Try using `ENTITY::_IS_ENTITY_FULLY_LOOTED(Entity entity)`
> 
> and if its false use `TASK::TASK_LOOT_ENTITY(Ped ped, Entity entity)` to loot it
> 
> then set it to looted afterwards using `ENTITY::_SET_ENTITY_FULLY_LOOTED(Entity entity, Bool looted)`
> 
> Of course this is just in theory, but it should work as long as you retrieve the nearest entity. If you can get it to function properly, try setting this as a looped command so it will auto-loot nearby entities.

I was going to use in more in an aspect for auto collecting spawned collectibles. but thank you for this i really couldnt figure it out yesterday. once i am done with player database, which is currently bugging tf out, i will work on this. there were so many feature requests made today 🤣

**Comment by Deadlineem** [comment]
> > > I tried to get this to work, using `TASK_PICKUP_CARRIABLE_ENTITY` but it didn't work.
> > 
> > 
> > @Rxann Try using `ENTITY::_IS_ENTITY_FULLY_LOOTED(Entity entity)`
> > and if its false use `TASK::TASK_LOOT_ENTITY(Ped ped, Entity entity)` to loot it
> > then set it to looted afterwards using `ENTITY::_SET_ENTITY_FULLY_LOOTED(Entity entity, Bool looted)`
> > Of course this is just in theory, but it should work as long as you retrieve the nearest entity. If you can get it to function properly, try setting this as a looped command so it will auto-loot nearby entities.
> 
> I was going to use in more in an aspect for auto collecting spawned collectibles. but thank you for this i really couldnt figure it out yesterday. once i am done with player database, which is currently bugging tf out, i will work on this. there were so many feature requests made today 🤣

No problem, yeah i saw alot of feature requests, ive been doing my own various little things in C++ to this menu on my end testing various things and getting them to work properly, i really like the way this is set up it makes it super easy to add new things to the menu, especially for someone new to C++ like myself.  If you have discord, you can feel free to add me on there, same username as github, im always open to passing ideas around.

**Comment by Rxann** [comment]
> > > > I tried to get this to work, using `TASK_PICKUP_CARRIABLE_ENTITY` but it didn't work.
> 
> > > 
> 
> > > 
> 
> > > @Rxann Try using `ENTITY::_IS_ENTITY_FULLY_LOOTED(Entity entity)`
> 
> > > and if its false use `TASK::TASK_LOOT_ENTITY(Ped ped, Entity entity)` to loot it
> 
> > > then set it to looted afterwards using `ENTITY::_SET_ENTITY_FULLY_LOOTED(Entity entity, Bool looted)`
> 
> > > Of course this is just in theory, but it should work as long as you retrieve the nearest entity. If you can get it to function properly, try setting this as a looped command so it will auto-loot nearby entities.
> 
> > 
> 
> > I was going to use in more in an aspect for auto collecting spawned collectibles. but thank you for this i really couldnt figure it out yesterday. once i am done with player database, which is currently bugging tf out, i will work on this. there were so many feature requests made today 🤣
> 
> 
> 
> No problem, yeah i saw alot of feature requests, ive been doing my own various little things in C++ to this menu on my end testing various things and getting them to work properly, i really like the way this is set up it makes it super easy to add new things to the menu, especially for someone new to C++ like myself.  If you have discord, you can feel free to add me on there, same username as github, im always open to passing ideas around.

oh yeah for sure. are you in the yimmenu element server? if not i can give you the link

**Comment by Deadlineem** [comment]
> > > > > I tried to get this to work, using `TASK_PICKUP_CARRIABLE_ENTITY` but it didn't work.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > @Rxann Try using `ENTITY::_IS_ENTITY_FULLY_LOOTED(Entity entity)`
> > 
> > 
> > > > and if its false use `TASK::TASK_LOOT_ENTITY(Ped ped, Entity entity)` to loot it
> > 
> > 
> > > > then set it to looted afterwards using `ENTITY::_SET_ENTITY_FULLY_LOOTED(Entity entity, Bool looted)`
> > 
> > 
> > > > Of course this is just in theory, but it should work as long as you retrieve the nearest entity. If you can get it to function properly, try setting this as a looped command so it will auto-loot nearby entities.
> > 
> > 
> > > 
> > 
> > 
> > > I was going to use in more in an aspect for auto collecting spawned collectibles. but thank you for this i really couldnt figure it out yesterday. once i am done with player database, which is currently bugging tf out, i will work on this. there were so many feature requests made today 🤣
> > 
> > 
> > No problem, yeah i saw alot of feature requests, ive been doing my own various little things in C++ to this menu on my end testing various things and getting them to work properly, i really like the way this is set up it makes it super easy to add new things to the menu, especially for someone new to C++ like myself.  If you have discord, you can feel free to add me on there, same username as github, im always open to passing ideas around.
> 
> oh yeah for sure. are you in the yimmenu element server? if not i can give you the link

I am but i dont use element, i joined for help once, ended up figuring it out on my own.

**Comment by Rxann** [comment]
> > > > > > I tried to get this to work, using `TASK_PICKUP_CARRIABLE_ENTITY` but it didn't work.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > @Rxann Try using `ENTITY::_IS_ENTITY_FULLY_LOOTED(Entity entity)`
> 
> > > 
> 
> > > 
> 
> > > > > and if its false use `TASK::TASK_LOOT_ENTITY(Ped ped, Entity entity)` to loot it
> 
> > > 
> 
> > > 
> 
> > > > > then set it to looted afterwards using `ENTITY::_SET_ENTITY_FULLY_LOOTED(Entity entity, Bool looted)`
> 
> > > 
> 
> > > 
> 
> > > > > Of course this is just in theory, but it should work as long as you retrieve the nearest entity. If you can get it to function properly, try setting this as a looped command so it will auto-loot nearby entities.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > I was going to use in more in an aspect for auto collecting spawned collectibles. but thank you for this i really couldnt figure it out yesterday. once i am done with player database, which is currently bugging tf out, i will work on this. there were so many feature requests made today 🤣
> 
> > > 
> 
> > > 
> 
> > > No problem, yeah i saw alot of feature requests, ive been doing my own various little things in C++ to this menu on my end testing various things and getting them to work properly, i really like the way this is set up it makes it super easy to add new things to the menu, especially for someone new to C++ like myself.  If you have discord, you can feel free to add me on there, same username as github, im always open to passing ideas around.
> 
> > 
> 
> > oh yeah for sure. are you in the yimmenu element server? if not i can give you the link
> 
> 
> 
> I am but i dont use element, i joined for help once, ended up figuring it out on my own.
> 
> 

Ah okay. i talk in there sometimes. i added u on discord btw.
