### ISSUE TITLE
[Request] Dead/Paralyzed Animals

### ISSUE THREAD

**Issue by bunnybuddy213** [YimMenu/HorseMenu#113]
I'm going to insist, but this option would be of the utmost importance!

**Comment by Rxann** [comment]
I'll add dead animals to the Ped Spawner Improvements pr.

**Comment by Rxann** [comment]
> @Rxann Well, while you're at it why not get it up to par with some p2c's? This would include the option to also spawn them frozen, invisible, with god mode, or with the model scale overridden. You may want to consider being able to delete spawned models as well.

Alright, I like a good challenge. I currently have frozen done. The others will be easy. Deleting models gave me a challenge before, but i can probably get it too work. Please don't merge this until I implement these things.

**Comment by bunnybuddy213** [comment]
> you

I created a discord for HorseMenu btw if you want to join bro

**Comment by Rxann** [comment]
> > > @Rxann Well, while you're at it why not get it up to par with some p2c's? This would include the option to also spawn them frozen, invisible, with god mode, or with the model scale overridden. You may want to consider being able to delete spawned models as well.
> 
> > 
> 
> > Alright, I like a good challenge. I currently have frozen done. The others will be easy. Deleting models gave me a challenge before, but i can probably get it too work. Please don't merge this until I implement these things.
> 
> 
> 
> what is your discord, if you don't mind sharing? I hardly have time nowadays to deal with this shit but I can give you some insight to make HIGH QUALITY horse memes. :')

it is `_rxan_` if it shows italicized after i put it in those it has underscores before and after rxan

**Comment by Rxann** [comment]
@DayibBaba this can be closed, ped spawner pr was merged.
