### ISSUE TITLE
[Bug]Recovery menu / Spawn won't scroll down

### ISSUE THREAD

**Issue by GrymRpr** [YimMenu/HorseMenu#114]
Latest dll.
When using the Recovery / Spawn section you are unable to scroll down past the bottom of the window.
![scrol18](https://github.com/YimMenu/HorseMenu/assets/125405315/16bf5ad0-4213-489b-a181-7cc2b60e263b)

**Comment by Rxann** [comment]
scroll when hovering in over the options. #102 improves this feature and makes it a dropdown
