### ISSUE TITLE
(Request) Infinite blue vision

### ISSUE THREAD

**Issue by rasleraketer** [YimMenu/HorseMenu#115]
The infinite blue vision would be great

**Comment by Rxann** [comment]
> The infinite blue vision would be great

elaborate

**Comment by Deadlineem** [comment]
> > The infinite blue vision would be great
> 
> elaborate

Hes talking about the tracker vision, when your tracking objectives or animals

**Comment by rasleraketer** [comment]
> > > La visión azul infinita sería genial.
> > 
> > 
> > elaborar
> 
> Está hablando de la visión del rastreador, cuando tus objetivos de seguimiento o animales

Exactly

**Comment by rasleraketer** [comment]
> > The infinite blue vision would be great
> 
> elaborate

As another user said, I mean the blue vision that we can use to track npc or listen to collectibles, I don't know what it's really called, it's like the eagle vision from Assasins creed

**Comment by Deadlineem** [comment]
PLAYER::_ENABLE_EAGLEEYE(Player player, Bool enable)

**Comment by Rxann** [comment]
> @Rxann 
> 
> PLAYER::_ENABLE_EAGLEEYE(Player player, Bool enable)

alright, if i cannot find anything in my ida dump tmrw i will figure out a way for this to work. do you know of any natives to see if you are in eagle eye, and furthermore to stop the drain of it?

**Comment by Deadlineem** [comment]
> > @Rxann
> > PLAYER::_ENABLE_EAGLEEYE(Player player, Bool enable)
> 
> alright, if i cannot find anything in my ida dump tmrw i will figure out a way for this to work. do you know of any natives to see if you are in eagle eye, and furthermore to stop the drain of it?
> 
> This can also be renamed Infinite Eagle Eye if you want.

PLAYER::_MODIFY_INFINITE_TRAIL_VISION(PLAYER::PLAYER_ID(), toggle);

this sets infinite eagle eye BUT it doesnt auto toggle eagle eye on for you.  still working things out but this will close this issue for sure.
