### ISSUE TITLE
[Bug] Max/Min Honor

### ISSUE THREAD

**Issue by bunnybuddy213** [YimMenu/HorseMenu#118]

**Comment by Deadlineem** [comment]
You need to add a description to these explaining more in depth what ytou experience @bunnybuddy213, I am aware that the buttons under network ( i think ) do not seem to do anything but if you go into the players list, click on yourself and go to the options, it works in there.

**Comment by Rxann** [comment]
> You need to add a description to these explaining more in depth what ytou experience @bunnybuddy213, I am aware that the buttons under network ( i think ) do not seem to do anything but if you go into the players list, click on yourself and go to the options, it works in there.

I do agree. We need some context, what feature was being used, and if you have tried other things such as what @Deadlineem has said above.
