### ISSUE TITLE
REQ: Weather and Time

### ISSUE THREAD

**Issue by dwsiddall** [YimMenu/HorseMenu#123]
I was asked to move these suggestions to this area by Ryan.

Ability to set the weather and make it hold or pause so the weather stays the same as long as needed.

Ability to set the time of day and make it hold or pause so the time stays the same as long as needed.

Thank you!

**Comment by Deadlineem** [comment]
@dwsiddall as far as weather goes, there is a PR that was submitted for this https://github.com/YimMenu/HorseMenu/pull/79

was never pushed yet but it was submitted.

**Comment by dwsiddall** [comment]
I am new to this.  Am I supposed to do something to, in essence, put my name in to say, "yes please" or "me too" or some kind of voting?

**Comment by Rxann** [comment]
> I am new to this.  Am I supposed to do something to, in essence, put my name in to say, "yes please" or "me too" or some kind of voting?

No not really. If you would like to express the want for a feature you can say something like that but conventionally you don't normally say that. These are also a place to talk about possible implementations and such.
