### ISSUE TITLE
[UI Improvement Idea] Changes to the UI for overall improvement

### ISSUE THREAD

**Issue by Deadlineem** [YimMenu/HorseMenu#125]
I have an idea to rework the UI a bit, so instead of 4, there are 2 columns on the self tab, and those columns themselves have tabs for various things.  The tabs would be miniature versions of the tabs at the top in the self menu (Main, Horse, Train, Animations, Recovery)

For example, under the Tools column, youll have mini tabs, same with the Column to toggle Global options (godmode, etc.)

Tools > Player
Tools > Law
Tools > Vehicles
Tools > Mount
Tools > NPC

(Photoshop created preview of the idea)
![Screenshot_32](https://github.com/YimMenu/HorseMenu/assets/24372625/fa15f8e6-8197-4f8e-8172-839b3d82a012)

and figure out how to get the buttons/toggles to run on the sameline via imgui

ImGui::SameLine();

would open up a whole lot of unused space and leave room for more options, I think it would be helpful for the future expansion of HorseMenu in general.

**Comment by Deadlineem** [comment]
> So you mean to add submenus to groups? Some sort of a tabbar within the groups. Wouldn't that make for inefficient navigation?

When i get out of work tonight ill toss the current styling into adobe and throw something together to better explain this idea for ya.

**Comment by Rxann** [comment]
> > So you mean to add submenus to groups? Some sort of a tabbar within the groups. Wouldn't that make for inefficient navigation?
> 
> 
> 
> When i get out of work tonight ill toss the current styling into adobe and throw something together to better explain this idea for ya.

I would like to see this concept, it will be interesting. I am not talented enough to be able to make sketches and stuff

**Comment by Deadlineem** [comment]
@DayibBaba So here is a photoshop mockup of what I am referring to, I will add this to the original post as well in case anyone else has any comments on it.
![Screenshot_32](https://github.com/YimMenu/HorseMenu/assets/24372625/fa15f8e6-8197-4f8e-8172-839b3d82a012)

**Comment by Rxann** [comment]
Closed by the rewrite of the UI in PR #161
