### ISSUE TITLE
[Feature Request]  Gain control of Entities

### ISSUE THREAD

**Issue by Deadlineem** [YimMenu/HorseMenu#127]
I am trying to gain control of another player to set their outfit variation (which will get rid of the players hat) and then cage them, but it seems theres no way to migrate the network ID's?

I've tried damn near everything i can think of which leads me to 2 possibilities

1.  The fact there is no NETWORK_ID_CAN_MIGRATE native is causing the entire issue

OR

2.  Not having Host/Script host privileges could be causing it to fail.

This script works as intended on myself, but not on others.  The reason we need to remove the hat is because the hat is considered a pickup or object, resulting in the cage floating above the players head and not attaching to the ground as it should.  Again, this ONLY happens while the player is wearing a hat.

```
namespace YimMenu::Features
{
    class CagePlayerSmall : public PlayerCommand
    {
        using PlayerCommand::PlayerCommand;

        virtual void OnCall(Player player) override
        {
            const Hash model = MISC::GET_HASH_KEY("p_prisoncage02x");

            Vector3 coords = ENTITY::GET_ENTITY_COORDS(PLAYER::GET_PLAYER_PED_SCRIPT_INDEX(player.GetId()), true, true);

            if (!NETWORK::NETWORK_HAS_CONTROL_OF_ENTITY(PLAYER::GET_PLAYER_PED_SCRIPT_INDEX(player.GetId()))) {
                int netID = NETWORK::NETWORK_GET_NETWORK_ID_FROM_ENTITY(PLAYER::GET_PLAYER_PED_SCRIPT_INDEX(player.GetId()));

                // Try to request control of the player's ped entity
                NETWORK::NETWORK_REQUEST_CONTROL_OF_ENTITY(PLAYER::GET_PLAYER_PED_SCRIPT_INDEX(player.GetId()));
                NETWORK::NETWORK_REQUEST_CONTROL_OF_NETWORK_ID(netID);

                // Check again if control has been obtained
                if (NETWORK::NETWORK_HAS_CONTROL_OF_ENTITY(PLAYER::GET_PLAYER_PED_SCRIPT_INDEX(player.GetId()))) {
                    // Change player's outfit
                    PED::_SET_RANDOM_OUTFIT_VARIATION(PLAYER::GET_PLAYER_PED_SCRIPT_INDEX(player.GetId()), 0);
                    ScriptMgr::Yield();

                    // Cage the player
                    Object obj = OBJECT::CREATE_OBJECT_NO_OFFSET(model, coords.x, coords.y, coords.z, true, true, false, false);
                    OBJECT::PLACE_OBJECT_ON_GROUND_PROPERLY(obj, 1.0f);
                } else {
                    // If control couldn't be obtained, handle the error (retry, show notification, etc.)
                    Notifications::Show("Request Control", "Failed to gain control of the player, cage has not been spawned.", NotificationType::Error);
                }
            } else {
                // If control was already obtained, proceed with outfit change and cage creation
                PED::_SET_RANDOM_OUTFIT_VARIATION(PLAYER::GET_PLAYER_PED_SCRIPT_INDEX(player.GetId()), false);
                ScriptMgr::Yield();

                // Cage the player
                Object obj = OBJECT::CREATE_OBJECT_NO_OFFSET(model, coords.x, coords.y, coords.z, true, true, false, false);
                OBJECT::PLACE_OBJECT_ON_GROUND_PROPERLY(obj, 1.0f);
            }
        }
    };

    static CagePlayerSmall _CagePlayerSmall{"cageplayersmall", "Cage (Small)", "Cages the player using a small cage"};
}
```

**Comment by Rxann** [comment]
Not related, but you can use player.GetPed().GetHandle() instead of the ped script index thing

**Comment by DayibBaba** [comment]
You cannot gain control of other player peds.

**Comment by Deadlineem** [comment]
> You cannot gain control of other player peds. Nor their current mount for that matter.

So in that instance, its not like gta, that sucks,  i did also attempt several other ways of caging, it seems forcing the object to -1.2 ( on foot ) and -2.2 (mounted) makes the cages spawn as proper as possible, however, placing them on the ground properly using the native results in the cage glitching out as i mentioned to @Rxann via discord.

Ive also tried attaching the object to the players feet, same general result, sometimes it places correctly.  Its a bummer that we cant control other players to remove that damn hat, such a nuisance lol

**Comment by Rxann** [comment]
> > You cannot gain control of other player peds. Nor their current mount for that matter.
> 
> 
> 
> So in that instance, its not like gta, that sucks,  i did also attempt several other ways of caging, it seems forcing the object to -1.2 ( on foot ) and -2.2 (mounted) makes the cages spawn as proper as possible, however, placing them on the ground properly using the native results in the cage glitching out as i mentioned to @Rxann via discord.
> 
> 
> 
> Ive also tried attaching the object to the players feet, shooting a single bullet from coords and various other attempts, same general result, sometimes it places correctly.  Its a bummer that we cant control other players to remove that damn hat, such a nuisance lol

I think i did figure it out. Check new pr commit

**Comment by DayibBaba** [comment]
> > You cannot gain control of other player peds. Nor their current mount for that matter.
> 
> So in that instance, its not like gta, that sucks, i did also attempt several other ways of caging, it seems forcing the object to -1.2 ( on foot ) and -2.2 (mounted) makes the cages spawn as proper as possible, however, placing them on the ground properly using the native results in the cage glitching out as i mentioned to @Rxann via discord.
> 
> Ive also tried attaching the object to the players feet, shooting a single bullet from coords and various other attempts, same general result, sometimes it places correctly. Its a bummer that we cant control other players to remove that damn hat, such a nuisance lol

This issue is not dissimilar to gta. Control over player peds has been patched ages ago.

**Comment by Rxann** [comment]
> > > You cannot gain control of other player peds. Nor their current mount for that matter.
> 
> > 
> 
> > So in that instance, its not like gta, that sucks, i did also attempt several other ways of caging, it seems forcing the object to -1.2 ( on foot ) and -2.2 (mounted) makes the cages spawn as proper as possible, however, placing them on the ground properly using the native results in the cage glitching out as i mentioned to @Rxann via discord.
> 
> > 
> 
> > Ive also tried attaching the object to the players feet, shooting a single bullet from coords and various other attempts, same general result, sometimes it places correctly. Its a bummer that we cant control other players to remove that damn hat, such a nuisance lol
> 
> 
> 
> This issue is not dissimilar to gta. Control over player peds has been patched ages ago.

What is the purpose of requesting control on a player ped? If you request control then for example, give the ped a task, will it work?

**Comment by DayibBaba** [comment]
> What is the purpose of requesting control on a player ped? If you request control then for example, give the ped a task, will it work?

I repeat, requesting control does not work on player peds or mounts, ergo the answer to your question is a resounding No.

**Comment by Rxann** [comment]
> > What is the purpose of requesting control on a player ped? If you request control then for example, give the ped a task, will it work?
> 
> 
> 
> I repeat, requesting control does not work on player peds or mounts, ergo the answer to your question is a resounding No.
> 
> 
> 
> 

Ah okay, I see. Thanks.
