### ISSUE TITLE
New DLL releases: Are the changes listed somewhere?

### ISSUE THREAD

**Issue by dwsiddall** [YimMenu/HorseMenu#129]
.
I saw a new DLL was released yesterday....I got it (and the new package too) and tried it but wasn't sure what was different.

Is there a place that lists what changes are reflected in the new releases?

Thank you.

**Comment by Rxann** [comment]
> .
> 
> I saw a new DLL was released yesterday....I got it (and the new package too) and tried it but wasn't sure what was different.
> 
> 
> 
> Is there a place that lists what changes are reflected in the new releases?
> 
> 
> 
> Thank you.
> 
> 
> 
> 

No, it would be relatively complex and tedious to do this for every release.

**Comment by dwsiddall** [comment]
I only meant really basic things like, "Spawn Wagon Added" or "Ignore NPC Added"

**Comment by Yimura** [comment]
The commit history exists, that’s why it’s important to properly title PR’s and individual commits to give context to what you’re doing.

https://github.com/YimMenu/HorseMenu/commits/master/

**Comment by Rxann** [comment]
> I only meant really basic things like, "Spawn Wagon Added" or "Ignore NPC Added"

I agree with what Yimura said below, the commit history is a good place to look.

**Comment by dwsiddall** [comment]
Thanks.

**Comment by Rxann** [comment]
> Thanks.

Your welcome. This can be closed.
