### ISSUE TITLE
[Request]  Block Explosion Spam/Update unknown task blocking

### ISSUE THREAD

**Issue by Deadlineem** [YimMenu/HorseMenu#131]
[08:11:43.8507177][WARN/ShouldBlockSync.cpp:340] Blocked unknown task crash from ~e~Hades
[08:11:43.8507781][WARN/ShouldBlockSync.cpp:340] Blocked unknown task crash from ~e~Hades
[08:11:43.8509217][WARN/ShouldBlockSync.cpp:340] Blocked unknown task crash from Dabberdanny420
[08:11:43.8509825][WARN/ShouldBlockSync.cpp:340] Blocked unknown task crash from Dabberdanny420
[08:11:43.8529191][WARN/ShouldBlockSync.cpp:340] Blocked unknown task crash from Dabberdanny420
[08:11:43.8530052][WARN/ShouldBlockSync.cpp:340] Blocked unknown task crash from Dabberdanny420
[08:11:43.9142170][WARN/ShouldBlockSync.cpp:340] Blocked unknown task crash from Dabberdanny420
[08:11:43.9142545][WARN/ShouldBlockSync.cpp:340] Blocked unknown task crash from Dabberdanny420
[08:11:43.9142988][WARN/ShouldBlockSync.cpp:340] Blocked unknown task crash from Dabberdanny420
[08:11:43.9143256][WARN/ShouldBlockSync.cpp:340] Blocked unknown task crash from Dabberdanny420
[08:11:43.9158171][WARN/HandleNetGameEvent.cpp:74] Blocked NETWORK_CLEAR_PED_TASKS_EVENT from ~e~Hades
[08:11:43.9862921][WARN/ShouldBlockSync.cpp:340] Blocked unknown task crash from Drippp26
[08:11:43.9869480][WARN/ShouldBlockSync.cpp:340] Blocked unknown task crash from Kooper1010
[08:11:43.9869905][WARN/ShouldBlockSync.cpp:340] Blocked unknown task crash from Kooper1010
[08:11:43.9870248][WARN/ShouldBlockSync.cpp:340] Blocked unknown task crash from Kooper1010
[08:11:43.9870765][WARN/ShouldBlockSync.cpp:340] Blocked unknown task crash from Kooper1010
[08:11:43.9891582][ERROR/ExceptionHandler.cpp:43] EXCEPTION_ACCESS_VIOLATION
Dumping modules:
RDR2.exe Base Address: 0x7FF60B9B0000 Size: 121206272
ntdll.dll Base Address: 0x7FF96E730000 Size: 1249280
KERNEL32.DLL Base Address: 0x7FF96E440000 Size: 528384
KERNELBASE.dll Base Address: 0x7FF96BAA0000 Size: 1638400
USER32.dll Base Address: 0x7FF96CFA0000 Size: 610304
win32u.dll Base Address: 0x7FF96C0A0000 Size: 49152
GDI32.dll Base Address: 0x7FF96DE20000 Size: 57344
gdi32full.dll Base Address: 0x7FF96C1F0000 Size: 675840
msvcp_win.dll Base Address: 0x7FF96BE50000 Size: 335872
ucrtbase.dll Base Address: 0x7FF96C0D0000 Size: 798720
WS2_32.dll Base Address: 0x7FF96C480000 Size: 290816
RPCRT4.dll Base Address: 0x7FF96DFA0000 Size: 880640
CRYPT32.dll Base Address: 0x7FF96C310000 Size: 1134592
WINTRUST.dll Base Address: 0x7FF96BEF0000 Size: 307200
IPHLPAPI.DLL Base Address: 0x7FF96A520000 Size: 122880
DSOUND.dll Base Address: 0x7FF8FC9B0000 Size: 491520
WINMM.dll Base Address: 0x7FF95D600000 Size: 114688
msvcrt.dll Base Address: 0x7FF96E2C0000 Size: 507904
advapi32.dll Base Address: 0x7FF96E5D0000 Size: 434176
IMM32.dll Base Address: 0x7FF96DE50000 Size: 126976
sechost.dll Base Address: 0x7FF96E510000 Size: 446464
combase.dll Base Address: 0x7FF96DA90000 Size: 2539520
SHELL32.dll Base Address: 0x7FF96C6A0000 Size: 6848512
MF.dll Base Address: 0x7FF95E900000 Size: 372736
MFPlat.DLL Base Address: 0x7FF95E730000 Size: 1503232
shcore.dll Base Address: 0x7FF96DEA0000 Size: 684032
ole32.dll Base Address: 0x7FF96D8F0000 Size: 909312
OLEAUT32.dll Base Address: 0x7FF96C570000 Size: 647168
MFReadWrite.dll Base Address: 0x7FF90F400000 Size: 995328
PROPSYS.dll Base Address: 0x7FF966910000 Size: 692224
COMCTL32.dll Base Address: 0x7FF94B910000 Size: 1998848
ResampleDmo.DLL Base Address: 0x7FF8FC8F0000 Size: 503808
DINPUT8.dll Base Address: 0x7FF9417C0000 Size: 176128
XINPUT9_1_0.dll Base Address: 0x7FF968CC0000 Size: 8192
oo2core_5_win64.dll Base Address: 0x7FF914110000 Size: 739840
amd_ags_x64.dll Base Address: 0x7FF952510000 Size: 103424
CFGMGR32.dll Base Address: 0x7FF96B7B0000 Size: 221184
WTSAPI32.dll Base Address: 0x7FF96A850000 Size: 40960
d3d9.dll Base Address: 0x7FF943090000 Size: 1306624
NvLowLatencyVk.dll Base Address: 0x7FF963440000 Size: 28160
ffx_fsr2_api_x64.dll Base Address: 0x7FF963480000 Size: 16896
powrprof.dll Base Address: 0x7FF96B3B0000 Size: 77824
ffx_fsr2_api_dx12_x64.dll Base Address: 0x7FF8DDBE0000 Size: 26624
bcrypt.dll Base Address: 0x7FF96B430000 Size: 110592
ffx_fsr2_api_vk_x64.dll Base Address: 0x7FF8FA9A0000 Size: 28160
VERSION.dll Base Address: 0x7FF963B30000 Size: 12288
bink2w64.dll Base Address: 0x7FF933B60000 Size: 260608
winmmbase.dll Base Address: 0x7FF95E990000 Size: 102400
dwmapi.dll Base Address: 0x7FF969230000 Size: 90112
msdmo.dll Base Address: 0x7FF931420000 Size: 16384
VCRUNTIME140.dll Base Address: 0x7FF9503F0000 Size: 73728
MSVCP140.dll Base Address: 0x7FF941660000 Size: 340480
VCRUNTIME140_1.dll Base Address: 0x7FF959160000 Size: 15360
vulkan-1.dll Base Address: 0x7FF90C430000 Size: 1031168
MFCORE.DLL Base Address: 0x7FF95A180000 Size: 3026944
dxcore.dll Base Address: 0x7FF9690E0000 Size: 131072
CRYPTBASE.DLL Base Address: 0x7FF96B200000 Size: 12288
UMPDC.dll Base Address: 0x7FF96B2F0000 Size: 36864
kernel.appcore.dll Base Address: 0x7FF96AAA0000 Size: 36864
bcryptPrimitives.dll Base Address: 0x7FF96BF60000 Size: 376832
RTWorkQ.DLL Base Address: 0x7FF959490000 Size: 102400
MSASN1.dll Base Address: 0x7FF96B740000 Size: 36864
dxgi.dll Base Address: 0x7FF969120000 Size: 651264
inputhost.dll Base Address: 0x7FF94BFD0000 Size: 1540096
CoreMessaging.dll Base Address: 0x7FF968A20000 Size: 860160
directxdatabasehelper.dll Base Address: 0x7FF9651F0000 Size: 196608
cryptnet.dll Base Address: 0x7FF963AC0000 Size: 139264
drvstore.dll Base Address: 0x7FF9638A0000 Size: 1044480
devobj.dll Base Address: 0x7FF96B760000 Size: 110592
wldp.dll Base Address: 0x7FF96B290000 Size: 188416
imagehlp.dll Base Address: 0x7FF96E240000 Size: 49152
CRYPTSP.dll Base Address: 0x7FF96B1E0000 Size: 57344
rsaenh.dll Base Address: 0x7FF96AA00000 Size: 147456
nvgpucomp64.dll Base Address: 0x7FF95AA20000 Size: 29258752
windows.storage.dll Base Address: 0x7FF9699C0000 Size: 7032832
wintypes.dll Base Address: 0x7FF969880000 Size: 544768
shlwapi.dll Base Address: 0x7FF96E690000 Size: 212992
nvspcap64.dll Base Address: 0x7FF90E2C0000 Size: 2056192
profapi.dll Base Address: 0x7FF96B9D0000 Size: 90112
ntmarta.dll Base Address: 0x7FF96AAC0000 Size: 147456
uxtheme.dll Base Address: 0x7FF968FB0000 Size: 425984
Setupapi.dll Base Address: 0x7FF96D320000 Size: 913408
nvapi64.dll Base Address: 0x7FF957CF0000 Size: 5633024
nvcuda64.dll Base Address: 0x7FF8D4700000 Size: 6232576
clbcatq.dll Base Address: 0x7FF96E390000 Size: 471040
amsi.dll Base Address: 0x7FF95FC90000 Size: 57344
USERENV.dll Base Address: 0x7FF96B080000 Size: 102400
MpOav.dll Base Address: 0x7FF939980000 Size: 212992
EOSSDK-Win64-Shipping.dll Base Address: 0x7FF8D5380000 Size: 7229440
WLDAP32.dll Base Address: 0x7FF96C500000 Size: 282624
Normaliz.dll Base Address: 0x7FF96CF00000 Size: 4096
WINHTTP.dll Base Address: 0x7FF965970000 Size: 987136
Secur32.dll Base Address: 0x7FF96A870000 Size: 12288
SSPICLI.DLL Base Address: 0x7FF96AD00000 Size: 126976
NSI.dll Base Address: 0x7FF96DE90000 Size: 8192
dhcpcsvc6.DLL Base Address: 0x7FF9658C0000 Size: 28672
dhcpcsvc.DLL Base Address: 0x7FF965880000 Size: 69632
mswsock.dll Base Address: 0x7FF96AF20000 Size: 331776
WINSTA.dll Base Address: 0x7FF96B010000 Size: 229376
napinsp.dll Base Address: 0x7FF940E20000 Size: 53248
pnrpnsp.dll Base Address: 0x7FF940E00000 Size: 69632
DNSAPI.dll Base Address: 0x7FF96A590000 Size: 737280
winrnr.dll Base Address: 0x7FF940DE0000 Size: 32768
wshbth.dll Base Address: 0x7FF9649A0000 Size: 45056
nlansp_c.dll Base Address: 0x7FF940DB0000 Size: 81920
D3D12.DLL Base Address: 0x7FF949BC0000 Size: 102400
D3D12Core.dll Base Address: 0x7FF8DF240000 Size: 1351680
D3DSCache.dll Base Address: 0x7FF93BEB0000 Size: 106496
twinapi.appcore.dll Base Address: 0x7FF9629B0000 Size: 1855488
windows.staterepositorycore.dll Base Address: 0x7FF960F80000 Size: 57344
nvoglv64.dll Base Address: 0x7FF8D94F0000 Size: 21276672
rometadata.dll Base Address: 0x7FF94C210000 Size: 157184
SocialClubVulkanLayer.dll Base Address: 0x7FF917D50000 Size: 217600
EOSOVH-Win64-Shipping.dll Base Address: 0x7FF90E820000 Size: 531456
d3d11.dll Base Address: 0x7FF967B60000 Size: 1867776
OPENGL32.dll Base Address: 0x7FF90F270000 Size: 798720
GLU32.dll Base Address: 0x7FF9109B0000 Size: 126976
MMDevApi.dll Base Address: 0x7FF961700000 Size: 462848
wdmaud.drv Base Address: 0x7FF90C340000 Size: 200704
ksuser.dll Base Address: 0x7FF94A800000 Size: 8192
AVRT.dll Base Address: 0x7FF965C00000 Size: 8192
AUDIOSES.DLL Base Address: 0x7FF953390000 Size: 1409024
msacm32.drv Base Address: 0x7FF94A7F0000 Size: 20480
MSACM32.dll Base Address: 0x7FF90C320000 Size: 77824
midimap.dll Base Address: 0x7FF911FA0000 Size: 16384
AudioDevProps2.dll Base Address: 0x7FF9401B0000 Size: 630272
MSCTF.dll Base Address: 0x24289F10000 Size: 1073152
ProductInfo.dll Base Address: 0x7FF949EC0000 Size: 227840
ASM.Plugin.AudioDevProps2.dll Base Address: 0x7FF9493C0000 Size: 151040
textinputframework.dll Base Address: 0x7FF94EE20000 Size: 1015808
CoreUIComponents.dll Base Address: 0x7FF964A40000 Size: 2039296
NvCameraAllowlisting64.dll Base Address: 0x7FF8FA140000 Size: 491520
NvCamera64.dll Base Address: 0x7FF8D3E90000 Size: 4241408
HID.DLL Base Address: 0x7FF96A2C0000 Size: 24576
WindowsCodecs.dll Base Address: 0x7FF967340000 Size: 1331200
d3dcompiler_47_64.dll Base Address: 0x7FF8D3A80000 Size: 3922944
nvldumdx.dll Base Address: 0x7FF961130000 Size: 599040
NvMessageBus.dll Base Address: 0x7FF957670000 Size: 2750976
nvwgf2umx.dll Base Address: 0x7FF953580000 Size: 20642304
DispBroker.dll Base Address: 0x7FF961FA0000 Size: 368640
AppXDeploymentClient.dll Base Address: 0x7FF965050000 Size: 815104
nvppex.dll Base Address: 0x7FF8F66D0000 Size: 728576
MessageBus.dll Base Address: 0x7FF951880000 Size: 5349888
dcomp.dll Base Address: 0x7FF9683B0000 Size: 1769472
XInput1_4.dll Base Address: 0x7FF948490000 Size: 32768
wbemprox.dll Base Address: 0x7FF962CC0000 Size: 28672
wbemcomn.dll Base Address: 0x7FF962C40000 Size: 311296
wbemsvc.dll Base Address: 0x7FF9601B0000 Size: 8192
fastprox.dll Base Address: 0x7FF960220000 Size: 708608
gpapi.dll Base Address: 0x7FF96AFB0000 Size: 77824
nvngx.dll Base Address: 0x7FF914880000 Size: 359936
_nvngx.dll Base Address: 0x7FF8D51E0000 Size: 712704
DEVRTL.dll Base Address: 0x7FF963570000 Size: 45056
SPINF.dll Base Address: 0x7FF95EC10000 Size: 73728
resourcepolicyclient.dll Base Address: 0x7FF969570000 Size: 36864
Windows.UI.dll Base Address: 0x7FF94F0D0000 Size: 966656
fwpuclnt.dll Base Address: 0x7FF964910000 Size: 294912
rasadhlp.dll Base Address: 0x7FF963180000 Size: 8192
WINNSI.DLL Base Address: 0x7FF969070000 Size: 16384
socialclub.dll Base Address: 0x7FF90E8E0000 Size: 2702336
WININET.dll Base Address: 0x7FF95A520000 Size: 2113536
chrome_elf.dll Base Address: 0x7FF93D5E0000 Size: 901120
libcef.dll Base Address: 0x7FF8C1FF0000 Size: 151009280
COMDLG32.dll Base Address: 0x7FF96E0C0000 Size: 778240
OLEACC.dll Base Address: 0x7FF94B770000 Size: 274432
UIAutomationCore.DLL Base Address: 0x7FF9475B0000 Size: 3063808
dbghelp.dll Base Address: 0x7FF962EF0000 Size: 1646592
ncrypt.dll Base Address: 0x7FF96B400000 Size: 114688
WINSPOOL.DRV Base Address: 0x7FF94B860000 Size: 405504
DWrite.dll Base Address: 0x7FF9678E0000 Size: 1650688
NETAPI32.dll Base Address: 0x7FF961A80000 Size: 49152
dxva2.dll Base Address: 0x7FF949360000 Size: 102400
USP10.dll Base Address: 0x7FF949340000 Size: 4096
urlmon.dll Base Address: 0x7FF94D320000 Size: 1298432
wevtapi.dll Base Address: 0x7FF9656B0000 Size: 282624
credui.dll Base Address: 0x7FF949190000 Size: 65536
CRYPTUI.dll Base Address: 0x7FF961680000 Size: 278528
ESENT.dll Base Address: 0x7FF94AB80000 Size: 3145728
netutils.dll Base Address: 0x7FF96A510000 Size: 20480
srvcli.dll Base Address: 0x7FF961650000 Size: 57344
iertutil.dll Base Address: 0x7FF9511C0000 Size: 557056
DSROLE.DLL Base Address: 0x7FF96A750000 Size: 8192
WKSCLI.DLL Base Address: 0x7FF9651D0000 Size: 49152
SAMCLI.DLL Base Address: 0x7FF957CD0000 Size: 61440
NTASN1.dll Base Address: 0x7FF96B370000 Size: 69632
FirewallAPI.dll Base Address: 0x7FF96A430000 Size: 385024
fwbase.dll Base Address: 0x7FF96A3B0000 Size: 208896
FWPolicyIOMgr.dll Base Address: 0x7FF95E650000 Size: 245760
ondemandconnroutehelper.dll Base Address: 0x7FF93CB20000 Size: 45056
HorseMenu.dll Base Address: 0x7FF8D31A0000 Size: 2560000
D3DCOMPILER_47.dll Base Address: 0x7FF9674F0000 Size: 3043328
Dumping registers:
RAX: 0x0
RCX: 0x401000
RDX: 0x9A18DCBCE8
RBX: 0x249FB00C620
RSI: 0x242A77E5D40
RDI: 0x242A77E5D40
RSP: 0x9A18DCB7E0
RBP: 0x9A18DCB8E0
R8:  0x242B9672580
R9:  0x1
R10: 0x3
R11: 0x9A18DCB700
R12: 0x242A77E5D40
R13: 0x249FB00C630
R14: 0x0
R15: 0x242A77E5D00
Dumping stacktrace:
[0]	EOSOVH-Win64-Shipping.dll+0x2BD12 0x7FF90E84BD12
[1]	EOSOVH-Win64-Shipping.dll+0x39A5B 0x7FF90E859A5B
[2]	nvoglv64.dll DrvPresentBuffers
[3]	vulkan-1.dll vkResetEvent
[4]	vulkan-1.dll vkResetEvent
[5]	C:\Users\saiya\source\repos\Deadlineem\HorseMenu\src\core\renderer\Renderer.cpp L: 211 YimMenu::Renderer::InitVulkan
[6]	C:\Users\saiya\source\repos\Deadlineem\HorseMenu\src\core\renderer\Renderer.cpp L: 768 YimMenu::Renderer::InitImpl
[7]	C:\Users\saiya\source\repos\Deadlineem\HorseMenu\src\main.cpp L: 35 YimMenu::Main
[8]	KERNEL32.DLL BaseThreadInitThunk
[9]	ntdll.dll RtlUserThreadStart
--------End of exception--------

**Comment by Rxann** [comment]
I have a drafted pr that I will be opening soon and it blocks explosion events
