### ISSUE TITLE
【BUG】After injecting HorseMenu, the fishing rod cannot be thrown out and fishing cannot be carried out.

### ISSUE THREAD

**Issue by yangzhchao** [YimMenu/HorseMenu#132]
After injecting HorseMenu, the fishing rod cannot be thrown out and fishing cannot be carried out.
I hope to fix it.
thanks

**Comment by Rxann** [comment]
At what point are you injecting? Could you send your settings file so I can try to reproduce?

**Comment by Deadlineem** [comment]
I have not tried to go fishing at all since i started using this.  I will give this a try and see if i can reproduce this myself as well

**Comment by yangzhchao** [comment]
After successfully injecting HorseMenu, opening the Infite Clip will reproduce the situation where the fishing rod cannot be thrown out.

[HorseMenu.zip](https://github.com/YimMenu/HorseMenu/files/14928358/HorseMenu.zip)

**Comment by Rxann** [comment]
> After successfully injecting HorseMenu, opening the Infite Clip will reproduce the situation where the fishing rod cannot be thrown out.
> 
> 
> 
> [HorseMenu.zip](https://github.com/YimMenu/HorseMenu/files/14928358/HorseMenu.zip)
> 
> 

Alright thanks, I'll check it out in a few minutes

**Comment by Deadlineem** [comment]
Solution is simple here

` {`weapon_fishingrod`,`group_fishingrod`,},                                                  -- {0xaba87754,0x60b51da4,},`

add a check against the fishing rod hash/joaat and if the fishing rod is held, make the script do nothing.
