### ISSUE TITLE
Settings system to save variables

### ISSUE THREAD

**Issue by DayibBaba** [YimMenu/HorseMenu#14]

**Comment by Hydra-Source** [comment]
std::map<string, std::any> :trollface:

**Comment by DayibBaba** [comment]
I could just port over the one from YimMenu as it works just great.

**Comment by Yimura** [comment]
The main downside of using that one is that changing one single line requires a full recompile of the menu.

It would be good to take a look at separating settings to their specific features.

**Comment by DayibBaba** [comment]
> The main downside of using that one is that changing one single line requires a full recompile of the menu.
> 
> It would be good to take a look at separating settings to their specific features.

Wouldn't having saving structs have their own file instead of hosting all in the `settings.hpp` file already suffice?

**Comment by Hydra-Source** [comment]
What about a dynamic container? It would definitely impact performance to some degree maybe noticeable maybe not but it would be very easy to save, load and edit.
