### ISSUE TITLE
Vulkan api support

### ISSUE THREAD

**Issue by tim-gromeyer** [YimMenu/HorseMenu#15]
Vulkan API Benefits:

1. **Performance Boost:** Vulkan has better performance for most users

2. **Linux Compatibility:** Unlike DirectX for Windows, Vulkan serves as a standard Linux graphics API. Converting DirectX10/11 to Vulkan (using DXVK) worked for YimMenu, but not for RDR2 due to crashes when using DirectX12

3. **User Empowerment:** Vulkan offers freedom for users to select graphics tech, enhancing personalization. Some exclusively use Vulkan due to errors (SteamDeck, also Windows users, see below)

4. **Developer Learning:** Learning Vulkan improves developer skills and knowledge.

Incorporating Vulkan into HorseMenu will (probably) provide better performance, Linux compatibility, and user satisfaction. With the emergence of SteamDeck, a Linux-based console, support for Linux/SteamDeck is important

**Comment by gir489returns** [comment]
Add one more item to it. Some people can only play in Vulkan. I get the following error if I try to use any of the DX varients.

![image](https://github.com/YimMenu/HorseMenu/assets/100792176/3576e998-89b4-4e35-b46b-c3483edd85c4)

**Comment by Hydra-Source** [comment]
Check PR #21
