### ISSUE TITLE
[Bug]: Change Time Crashes Game

### ISSUE THREAD

**Issue by Deadlineem** [YimMenu/HorseMenu#157]
### Describe the bug

Self explanatory

### Steps To Reproduce

Click change time

### Expected Behavior

changes the time.

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Epic Games

### Language

English

### Build

- [X] I've confirmed the issue exists on the latest version of HorseMenu

**Comment by Rxann** [comment]
Is your DLL up to date? Is your DLL from the master branch?

**Comment by Deadlineem** [comment]
> Is your DLL up to date? Is your DLL from the master branch?

I updated it right before playing last night, maybe it was a random happening but it instantly crashed me.

[cout.log](https://github.com/user-attachments/files/16073359/cout.log)

**Comment by Rxann** [comment]
We have noticed that this still happens
