### ISSUE TITLE
[Improvement]: Bring Players

### ISSUE THREAD

**Issue by Beginner555989** [YimMenu/HorseMenu#162]
### Which feature

plz add bring player 

### Reason

plz add bring player .. my friends want me to teleport them but i cant .. thank you a lot for the menu

**Comment by Rxann** [comment]
I will work on this and do some research on it for our next PR. In the mean time, spawn a wagon and then get your friend to get in it then teleport.

**Comment by Rxann** [comment]
I will close this issue when the change is made to the menu, until then I would like to keep it open.
