### ISSUE TITLE
Feature Wrappers

### ISSUE THREAD

**Issue by DayibBaba** [YimMenu/HorseMenu#17]
Before making any features, we need a wrapper system much like the [Commands System](https://github.com/YimMenu/YimMenu/tree/master/src/backend) from YimMenu.

**Comment by Hydra-Source** [comment]
Instead of 2 or 3 different systems like ticks, UI and commands a system that can do all would be very nice.

**Comment by DayibBaba** [comment]
> Instead of 2 or 3 different systems like ticks, UI and commands a system that can do all would be very nice.

I am working on something similar to this atm.
