### ISSUE TITLE
[Bug]: Failure to inject / Caught unwanted dependency / RDR2.exe+AEDE30

### ISSUE THREAD

**Issue by GrymRpr** [YimMenu/HorseMenu#172]
### Describe the bug

OS: Win 10 x64E
CPU: 10600k
GPU: 2080 STRIX
Latest drivers
Vulkan & DX12
This includes the latest nightly build

Starting last week, When injecting the game locks up with the console producing this error:
_[INFO/QueueDependency.cpp:52] Caught unwanted dependency: RDR2.exe+AEDE30_
_[WARN/Entity.cpp:30] IsValid() assertion failed for YimMenu::Entity::GetPosition_

This is the same under Vulkan & DX12

### Steps To Reproduce

1: Start game.
2: Load into MP Lobby (Camp)
3: Inject DLL
4: Games freezes up

### Expected Behavior

When injecting the dll the menu should work and not cause a crash

### Logs and/or screenshots

```
<paste your logs here>
```
[DX12.txt](https://github.com/user-attachments/files/16332371/DX12.txt)
[Vulcan.txt](https://github.com/user-attachments/files/16332384/Vulcan.txt)

### Store

Rockstar

### Language

English

### Additional context

The other _"Free"_ injects/works

### Build

- [X] I've confirmed the issue exists on the latest version of HorseMenu

**Comment by Rxann** [comment]
Yes, you are supposed to load the menu when you first load the game up, not when you are in online.
