### ISSUE TITLE
[Request]: Unlocking all outlaw pass items and adding role xp

### ISSUE THREAD

**Issue by TheLastBaytar** [YimMenu/HorseMenu#173]
### Solution

 Making a role xp giver like other recovery options.
Re-enabling old outlaw passes.

### Reason

I need to level up roles fast and unlock outlaw pass items.

**Comment by Rxann** [comment]
I am not sure, but I think R* might server side check the Outlaw Pass subscription. There are ways to add role xp, but I don't know them at the moment so that will need to be researched.

**Comment by tuyilmaz** [comment]
Adding role xp is possible using script functions. First define a script function:
```
static ScriptFunction GiveAward("net_main_offline"_J, "22 05 24")
```
Then call it with one of these award hashes:
- 0xB11109AB //200 trader + gold + xp
- 0xCBA92A55 //200 moonshiner + gold + xp
- 0x5424CC1A //200 bounty hunter + gold + xp
- 0xA64F15F2 //200 collector + xp + gold
- 0x05839847 //300 naturalist + xp

Example usage:
```
GiveAward(0xB11109AB, false, 255, 0, false)
```
This will give you 200 trader xp, some gold bars, and regular xp.

I don't know much about outlaw passes, but I saw their level up awards in a file. Unfortunately those are server only awards. They may be added using the NETSHOPPING natives. I saw some server only awards being sent to these natives in game scripts, but these natives are not documented and I don't really understand decompiled scripts.

**Comment by Rxann** [comment]
> decompiled

If I could ask, where did u find these hashes? I want to try to find more.

**Comment by tuyilmaz** [comment]
> > decompiled
> 
> If I could ask, where did u find these hashes? I want to try to find more.

`
update_4.rpf/x64/data/itemdatabase/catalog_awards_mp.rpf/catalog_awards_mp.ymt
`
I don't know if this file has everything, because another catalog_awards_mp.rpf is downloaded from Rockstar Games servers. You can find the link to it by searching "AwardsDatabase" in IDA. It also contains award multipliers.

**Comment by Rxann** [comment]
> > > decompiled
> > 
> > If I could ask, where did u find these hashes? I want to try to find more.
> 
> `
> update_4.rpf/x64/data/itemdatabase/catalog_awards_mp.rpf/catalog_awards_mp.ymt
> `
> I don't know if this file has everything, because another catalog_awards_mp.rpf is downloaded from Rockstar Games servers. You can find the link to it by searching "AwardsDatabase" in IDA. It also contains award multipliers.

Ok I am going to look for these

**Comment by Rxann** [comment]
I have information that the Outlaw Pass has been deprecated. @tuyilmaz would you say its fine to close this?

**Comment by tuyilmaz** [comment]
Definitely yes.
