### ISSUE TITLE
[Improvement]: Keep Bars Filled

### ISSUE THREAD

**Issue by Djizox** [YimMenu/HorseMenu#176]
### Which feature

**Keep bars filled:** split up so i still can die, but won't have to think about stamina and deadeye anymore. having health bar filled is almost like godmode, but can still only die to explosions and fall damage. 

### Reason

it would improve in a way for hiding the modding. you got refilled stats but can still be damaged. 

### Additional context

maybe a heal function to the context menu 😄 to heal friends.

**Comment by Rxann** [comment]
You can always use the `Hide Godmode` feature under Network -> Spoofing to basically just keep your health full.

**Comment by Rxann** [comment]
Let me know if this solves your issue.

**Comment by Djizox** [comment]
But how can I keep my bars filled except the health bar?
Infinite stamina and deadeye
Normal health?

**Comment by Djizox** [comment]
So we get a toggle for Health, Stamina and deadeye seperatly

**Comment by Djizox** [comment]
> You can always use the `Hide Godmode` feature under Network -> Spoofing to basically just keep your health full.

i don't want to have godmode on, either do i i want to heal every little damage. i want to have unlimited stamina and deadeye, and still be able to lose health and die. is it possible?

**Comment by Rxann** [comment]
> i don't want to have godmode on, either do i i want to heal every little damage. i want to have unlimited stamina and deadeye, and still be able to lose health and die. is it possible?

It is possible, I believe

**Comment by tuyilmaz** [comment]
It's pretty easy we just need to split "Keep Bars Filled" into three seperate features. I can do this, but creating a PR just for this seems unnecessary. It'd be better if someone includes this in their upcoming PRs.

**Comment by Rxann** [comment]
> It's pretty easy we just need to split "Keep Bars Filled" into three seperate features. I can do this, but creating a PR just for this seems unnecessary. It'd be better if someone includes this in their upcoming PRs.

I can do it.

**Comment by Rxann** [comment]
Closed by #210
