### ISSUE TITLE
[Build]: Compiler Error C2131

### ISSUE THREAD

**Issue by HELLLO1073** [YimMenu/HorseMenu#179]
### Describe the build issues

Every time I try and build the project with cmake in visual studio I get a C2131 error on every Pattern call only just got into cmake so was wondering if anyone knew a fix to it, have a image below.

### Screenshots and/or Logs

![Capture](https://github.com/user-attachments/assets/98a5cc1f-2f57-46da-9641-bb397cdd1dec)

### IDE/Compiler

Visual Studio 2022

### Additional context

Haven't modified anything, I've tried many things to fix it.

### HorseMenu Source Code

- [X] I've confirmed this is an issue with building unmodified HorseMenu.

**Comment by tuyilmaz** [comment]
That shouldn't cause the compiler to stop. I have the same errors, but it compiles without any problems.

**Comment by Yimura** [comment]
This is an intellisense error and not a build error. The Visual Studio Intellisense engine does not support all the latest features of the C++ coding language. Because YimMenu makes use of new features in the C++ standard these look like errors.

You can safely ignore these and build the project.

**Comment by HELLLO1073** [comment]
> This is an intellisense error and not a build error. The Visual Studio Intellisense engine does not support all the latest features of the C++ coding language. Because HorseMenu makes use of new features in the C++ standard these look like errors.
> 
> You can safely ignore these and build the project.

Every time I try building it it fails on the C2131 error and stops compiling with the line            
"FAILED: CMakeFiles/HorseMenu.dir/src/core/renderer/Renderer.cpp.obj - ninja: build stopped: subcommand failed."  

I use MSVC 19.30.30709.0 and cmake version 3.29.6

**Comment by Rxann** [comment]
> > This is an intellisense error and not a build error. The Visual Studio Intellisense engine does not support all the latest features of the C++ coding language. Because HorseMenu makes use of new features in the C++ standard these look like errors.
> > You can safely ignore these and build the project.
> 
> Every time I try building it it fails on the C2131 error and stops compiling with the line "FAILED: CMakeFiles/HorseMenu.dir/src/core/renderer/Renderer.cpp.obj - ninja: build stopped: subcommand failed."
> 
> I use MSVC 19.30.30709.0 and cmake version 3.29.6

Just use a precompiled binary if you can from the releases tab.

**Comment by HELLLO1073** [comment]
> > > This is an intellisense error and not a build error. The Visual Studio Intellisense engine does not support all the latest features of the C++ coding language. Because HorseMenu makes use of new features in the C++ standard these look like errors.
> > > You can safely ignore these and build the project.
> > 
> > 
> > Every time I try building it it fails on the C2131 error and stops compiling with the line "FAILED: CMakeFiles/HorseMenu.dir/src/core/renderer/Renderer.cpp.obj - ninja: build stopped: subcommand failed."
> > I use MSVC 19.30.30709.0 and cmake version 3.29.6
> 
> Just use a precompiled binary if you can from the releases tab.

I'd rather be able to compile this myself for a specific reason just thought someone might have a solution to it

**Comment by HELLLO1073** [comment]
anyone know of a possible fix to this please?

**Comment by HELLLO1073** [comment]
Fixed it thanks for the help!
