### ISSUE TITLE
[Request]: Protections that will teleport modders or whoever triggered the reaction to be teleported to where a death barrier I found (Kills even if your in god mode)

### ISSUE THREAD

**Issue by TexasToast03** [YimMenu/HorseMenu#196]
### Problem

Getting tired of other modders messing around with me and other people I'm with, so maybe you can add protections like how the YimMenu does. if people try to kick you, cage you, spawn a npc on you, teleport you somewhere, etc. etc.

### Solution

Teleport them to the death barrier as a reaction if kick dosn't work. I have the coordinates for the death barrier. 
Coordinates: 3166.51, 9838.82, -59.83

### Reason

To make it so modders have a harder time messing with us.

### Additional context

Could use death barrier for something else. Kills me even when I have god mode activated. Maybe have it be a repeated spawn loop or something.

**Comment by tuyilmaz** [comment]
I think other modders can easily block remote teleport

**Comment by TexasToast03** [comment]
okay but what if theres a way to maybe do it quick enough to where they go there for a second like if it tried to teleport them fast enough, or bring the barrier to them?

**Comment by TexasToast03** [comment]
Or if someone keeps killing your horse

**Comment by tuyilmaz** [comment]
I don't really know how remote teleport works, but I'm sure it is blocked before happening which means we can't "tp them there for a second". 

Bringing the barrier also seems not possible, but it'd be better if someone with more knowledge investigates this.

**Comment by TexasToast03** [comment]
> I don't really know how remote teleport works, but I'm sure it is blocked before happening which means we can't "tp them there for a second".
> 
> Bringing the barrier also seems not possible, but it'd be better if someone with more knowledge investigates this.

Alright, but also, like i said it would be nice if u could do that for regular players who just keep killing your horse

**Comment by Rxann** [comment]
> I don't really know how remote teleport works, but I'm sure it is blocked before happening which means we can't "tp them there for a second". 
> 
> Bringing the barrier also seems not possible, but it'd be better if someone with more knowledge investigates this.

We use the Vehicle Proximity Migration Node to put people in a vehicle and set the coords. It is blocked before it happens as you said.

**Comment by TexasToast03** [comment]
> > I don't really know how remote teleport works, but I'm sure it is blocked before happening which means we can't "tp them there for a second".
> > Bringing the barrier also seems not possible, but it'd be better if someone with more knowledge investigates this.
> 
> We use the Vehicle Proximity Migration Node to put people in a vehicle and set the coords. It is blocked before it happens as you said.

Damn, so no way to like force them onto a horse or npc and bring that horse/npc somewhere with them on it?

**Comment by Rxann** [comment]
No, It is not possible
