### ISSUE TITLE
[Build]: Injecting Issue

### ISSUE THREAD

**Issue by deodatokarol** [YimMenu/HorseMenu#203]
### Describe the build issues

While trying to inject the HorseMenu.dll i get this error shown in the picture i sent

### Screenshots and/or Logs

![Screenshot 2024-08-16 121325](https://github.com/user-attachments/assets/6f16f768-053b-485a-92b4-bf766ebf0924)

### IDE/Compiler

Visual Studio 2022

### HorseMenu Source Code

- [X] I've confirmed this is an issue with building unmodified HorseMenu.

**Comment by deodatokarol** [comment]
wait ima show the clip so that you can understand better

https://github.com/user-attachments/assets/66cecad9-e7cd-4d97-93ad-dbfa9ccc5152

**Comment by tuyilmaz** [comment]
Probably a problem with CE's injection method. Try using another injector like Xenos and see if it works.

**Comment by deodatokarol** [comment]
I tried also using xenos but i still get the same error

**Comment by Rxann** [comment]
> I tried also using xenos but i still get the same error

Screenshot your xenos settings please.

**Comment by deodatokarol** [comment]
![Screenshot 2024-08-16 155102](https://github.com/user-attachments/assets/d4c30004-a950-4af1-931a-72b025438060)

**Comment by Rxann** [comment]
Does it work when using a precompiled DLL from the github releases?

**Comment by deodatokarol** [comment]
what do you mean?

**Comment by deodatokarol** [comment]
oh ye i still get that error

**Comment by Rxann** [comment]
> oh ye i still get that error

It is likely a system issue and not a HorseMenu issue then. @tuyilmaz this should be resolved then.
