### ISSUE TITLE
[Request]: Ability to see R* admins in mp lobby ( SCTV Slots )

### ISSUE THREAD

**Issue by GrymRpr** [YimMenu/HorseMenu#208]
### Problem

Add the ability to see the 4 hidden Admin slots called SCTV on the menu's player list or at least the ability to inform when they are in use.

### Solution

Show on HorseMenu's Player list the hidden SCTV slots or, add an on-screen warning that an Admin is in that lobby using one of those slots or both.

### Reason

To provide a way to avoid R* admins as the menu provides a quick way to change sessions.

**Comment by GrymRpr** [comment]
> Are we sure that SCTV slots are even used in this game? From my research, I am not sure they are used.

I know it's a recently added option in another menu for Red Dead so I thought I'd inquire and with my limited knowledge I came up with SCTV as I've not seen anything else that fits that description while looking around. I know they have cheater monitoring in RDO so I took a guess as to how it's done.

**Comment by Rxann** [comment]
> 
> I know it's a recently added option in another menu for Red Dead so I thought I'd inquire and with my limited knowledge I came up with SCTV as I've not seen anything else that fits that description while looking around. I know they have cheater monitoring in RDO so I took a guess as to how it's done.

Which menu added it?

**Comment by GrymRpr** [comment]
> > I know it's a recently added option in another menu for Red Dead so I thought I'd inquire and with my limited knowledge I came up with SCTV as I've not seen anything else that fits that description while looking around. I know they have cheater monitoring in RDO so I took a guess as to how it's done.
> 
> Which menu added it?

Family Menu's new iteration "Rose" has a setting.
In it's "strengthening" section it has that option [ Detect Rockstar admin ] with it having a true/false setting in it's Settings.json

IF you plan on looking at that menu be warned. It's confirmed that it call's a server in China.

**Comment by AAA-ALR** [comment]
I'm sure this menu won't have what you said
```
switch (presence_hash)
{
case (uint32_t)PresenceEvents::PRESENCE_ADMIN_JOIN_EVENT:
{
	Notifications::Show("Presence Event", std::string("A Rockstar Games Admin ").append(sender_str).append(" is joining your game!"), NotificationType::Warning);
	LOG(WARNING) << "A Rockstar Games Admin(" << sender_str << ")"
	             << "is joining your game";
	break;
}
```
**It's just the SKID of Horse menu lol**

**Comment by GrymRpr** [comment]
> I'm sure this menu won't have what you said
> 
> ```
> switch (presence_hash)
> {
> case (uint32_t)PresenceEvents::PRESENCE_ADMIN_JOIN_EVENT:
> {
> 	Notifications::Show("Presence Event", std::string("A Rockstar Games Admin ").append(sender_str).append(" is joining your game!"), NotificationType::Warning);
> 	LOG(WARNING) << "A Rockstar Games Admin(" << sender_str << ")"
> 	             << "is joining your game";
> 	break;
> }
> ```
> 
> **It's just the SKID of Horse menu lol**

Wait...  Are you saying "ROSE" is just a badly implemented re-skinned HorseMenu?

**Comment by Rxann** [comment]
> Wait... Are you saying "ROSE" is just a badly implemented re-skinned HorseMenu?

Yes, It is a fork of HorseMenu. It's a worse fork of HorseMenu.

**Comment by GrymRpr** [comment]
> > Wait... Are you saying "ROSE" is just a badly implemented re-skinned HorseMenu?
> 
> Yes, It is a fork of HorseMenu. It's a worse fork of HorseMenu.

So, Not only did they try and outright steal / rename PlumbWicked's NameChanger twice (I staff His Discord) He's taken this code, Made it worse.  Encrypted it so no one can see and it calls a server [ mayixin dot com ] every time you use it

When they 1st released a screenshot of that rose menu I posted this in the vip section of PlumbWickeds Discord

![AlwaysA Thief](https://github.com/user-attachments/assets/9fc6d3b2-8330-4fe8-be51-6ef47a1e7f22)
Knew shenanigans were at play!.

Closed and Thanks again Rxann.
Damn thieves.
