### ISSUE TITLE
Change UI font

### ISSUE THREAD

**Issue by maybegreat48** [YimMenu/HorseMenu#30]

**Comment by Hydra-Source** [comment]
If contributors don't mind i can add a nice font i like statically.

**Comment by tyackman** [comment]
@Hydra-Source What do you have in mind?

**Comment by Hydra-Source** [comment]
> @Hydra-Source What do you have in mind?

![image](https://github.com/YimMenu/HorseMenu/assets/85032105/d9a745ed-d43a-45ae-a545-891212f12a45)
I don't know to be honest, just trying different styles :D
