### ISSUE TITLE
Hide godmode and spectator status

### ISSUE THREAD

**Issue by maybegreat48** [YimMenu/HorseMenu#49]

**Comment by Rxann** [comment]
Any clue on how hiding spectating could work? I have looked but there is no Camera Node like how hiding GTA spectating works.

**Comment by Rxann** [comment]
> > Any clue on how hiding spectating could work? I have looked but there is no Camera Node like how hiding GTA spectating works.
> 
> 
> 
> I'm not sure either, but P2Cs could be checking the camera position

Alright that would make sense. Off topic,do you think the rdr-classes repo may be outdated?
