### ISSUE TITLE
crash when catching unwanted dependency

### ISSUE THREAD

**Issue by tyackman** [YimMenu/HorseMenu#61]
[22:53:27.2553484][INFO/QueueDependency.cpp:52] Caught unwanted dependency: RDR2.exe+27F3254

This is all I got, there was no stack trace, this was also on my modified version, not vanilla horsemenu

Edit: this version was probably packed with themida forgot about that, sorry.

**Comment by tyackman** [comment]
Nope. Nothing has been hooked additionally.

**Comment by tyackman** [comment]
happened again(modified, packed version):
[16:29:31.0923931][INFO/QueueDependency.cpp:52] Caught unwanted dependency: RDR2.exe+ADE790

**Comment by tyackman** [comment]
It does have an anti-debugger thread running including the use of virtualalloc writewatch and some other common antidebugger memes. I'm calling ThreadHideFromDebugger on the debugger thread as well. Only feature I added to the menu that would remain on when I load the menu would be lawless mode (LAW::_SET_LAW_DISABLED). Ive also included cprlib to the cmake lists and use that for web requests. Binary packed using Themida. And incase u get any intrusive thoughts, no, I'm not selling this, its a meme for my friends and I l0l.

**Comment by tyackman** [comment]
Been testing without the anti-debugger and still caught @ RDR2.exe+ADE790. That leaves Themida on the table pretty much... I guess ill test without packing for a while

**Comment by xiaoxiao921** [comment]
You'll have to go further and match horsemenu code 1:1 and bisect all the way back to your current fork

**Comment by tyackman** [comment]
It happens on unmodified horsemenu as well. RDR2.exe+ADE790

**Comment by tyackman** [comment]
Slow brain moment lol. Thanks m8.
