### ISSUE TITLE
Add player database/block join

### ISSUE THREAD

**Issue by tyackman** [YimMenu/HorseMenu#62]
People suck. The block join feature shouldn't need to exist BUT...

**Comment by DayibBaba** [comment]
I believe RID joining was patched in rdr.

**Comment by tyackman** [comment]
Yes it apparently was, but I find myself in the lobby with frequented players no what matter my preference for matchmaking is set to. This can be quite aggravating when they jump from session to session to find & crash you to satisfy their bloodlust :(

**Comment by DayibBaba** [comment]
Kicks don't seem to be a thing. Crashes we don't do, however easy it seems to find some. So a block join would present a challenge if we are to implement one.

**Comment by tyackman** [comment]
There seems to be an implementation of this in fortitude. I would think writing the join response data would work pretty similarly to how it does in YimMenu for GTA, but can't say for sure, I've been unable to track down the functions down thus far. Maybe ill try again when I have time and motivation, but I'll leave this open for now, incase it catches someone's eye.

**Comment by Deadlineem** [comment]
Sounds like a good idea to mess with imo, at the very least the block join.  

Here is YimMenu's version and includes for reference to this, might help tossing something together.

```namespace big
{
	bool hooks::handle_join_request(Network* network, rage::snSession* session, rage::rlGamerInfo* player_info, CJoinRequestContext* ctx, BOOL is_transition_session)
	{
		if (auto player = g_player_database_service->get_player_by_rockstar_id(player_info->m_gamer_handle.m_rockstar_id);
		    player && player->block_join)
		{
			CMsgJoinResponse response{};
			response.m_status_code = player->block_join_reason;
			g_pointers->m_gta.m_write_join_response_data(&response, ctx->m_join_response_data, 512, &ctx->m_join_response_size);
			g_notification_service.push("BLOCK_JOIN"_T.data(),
			    std::vformat("BLOCK_JOIN_INFO"_T, std::make_format_args(player->name)));
			return false;
		}
		else
		{
			return g_hooking->get_original<hooks::handle_join_request>()(network, session, player_info, ctx, is_transition_session);
		}
	}
}```

Even just a simple button to lag the connection and push you into your own lobby would suffice.

**Comment by Rxann** [comment]
> Sounds like a good idea to mess with imo, at the very least the block join.  
> 
> 
> 
> Here is YimMenu's version and includes for reference to this, might help tossing something together.
> 
> 
> 
> ```#include "hooking/hooking.hpp"
> 
> #include "pointers.hpp"
> 
> #include "services/player_database/player_database_service.hpp"
> 
> 
> 
> #include <network/CJoinRequestContext.hpp>
> 
> #include <network/CMsgJoinResponse.hpp>
> 
> #include <network/snSession.hpp>
> 
> 
> 
> namespace big
> 
> {
> 
> 	bool hooks::handle_join_request(Network* network, rage::snSession* session, rage::rlGamerInfo* player_info, CJoinRequestContext* ctx, BOOL is_transition_session)
> 
> 	{
> 
> 		if (auto player = g_player_database_service->get_player_by_rockstar_id(player_info->m_gamer_handle.m_rockstar_id);
> 
> 		    player && player->block_join)
> 
> 		{
> 
> 			CMsgJoinResponse response{};
> 
> 			response.m_status_code = player->block_join_reason;
> 
> 			g_pointers->m_gta.m_write_join_response_data(&response, ctx->m_join_response_data, 512, &ctx->m_join_response_size);
> 
> 			g_notification_service.push("BLOCK_JOIN"_T.data(),
> 
> 			    std::vformat("BLOCK_JOIN_INFO"_T, std::make_format_args(player->name)));
> 
> 			return false;
> 
> 		}
> 
> 		else
> 
> 		{
> 
> 			return g_hooking->get_original<hooks::handle_join_request>()(network, session, player_info, ctx, is_transition_session);
> 
> 		}
> 
> 	}
> 
> }```
> 
> 
> 
> Even just a simple button to lag the connection and push you into your own lobby would suffice.

Yes, the problem is however that nodes that yimmenu uses do not exist in rdr2. I am no expert by far, but if you are host and block all of someone's syncs, that could maybe kick them.
