### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by Rxann** [YimMenu/HorseMenu#76]
I am loading the menu like normal, on the main branch. and then it just gives this stack trace. I did compile this on my pc, with debug mode on, but as I said it was a fresh branch.
[stacktrace.txt](https://github.com/YimMenu/HorseMenu/files/14440186/stacktrace.txt)

**Comment by Rxann** [comment]
fixed, will be opening pr w fix soon

**Comment by Hyman-R** [comment]
> fixed, will be opening pr w fix soon

Can you share a fixed binary release?  My load goes to crash too. Thanks.

**Comment by Rxann** [comment]
> > fixed, will be opening pr w fix soon
> 
> Can you share a fixed binary release? My load goes to crash too. Thanks.

I have a built version for this but unfortunately Github will not let me upload it. The best way would to be trying to get the PR merged which would then create a new release file with the fix included.

**Comment by Hyman-R** [comment]
> > > fixed, will be opening pr w fix soon
> > 
> > 
> > Can you share a fixed binary release? My load goes to crash too. Thanks.
> 
> I have a built version for this but unfortunately Github will not let me upload it. The best way would to be trying to get the PR merged which would then create a new release file with the fix included.

Understood. It seems that would take some time. Can share it with a Google Drive or some cloud storage? Thanks.

**Comment by Rxann** [comment]
> > > > fixed, will be opening pr w fix soon
> > > 
> > > 
> > > Can you share a fixed binary release? My load goes to crash too. Thanks.
> > 
> > 
> > I have a built version for this but unfortunately Github will not let me upload it. The best way would to be trying to get the PR merged which would then create a new release file with the fix included.
> 
> Understood. It seems that would take some time. Can share it with a Google Drive or some cloud storage? Thanks.

Yes, Here it is: [HorseMenu.dll](https://file.io/1ZCZUjNeqts9)

Let me know if there are any difficulties!

**Comment by Rxann** [comment]
@Hyman-R I have noticed there is a glitch when you resize the screen it may crash so I will be working to find a fix for that aswell

**Comment by Hyman-R** [comment]
> @Hyman-R I have noticed there is a glitch when you resize the screen it may crash so I will be working to find a fix for that aswell

Get it, that's why I find the file has been deleted. Sure, wait for the updated version. Thanks!

**Comment by Rxann** [comment]
> > @Hyman-R I have noticed there is a glitch when you resize the screen it may crash so I will be working to find a fix for that aswell
> 
> 
> 
> Get it, that's why I find the file has been deleted. Sure, wait for the updated version. Thanks!

I'm trying my best to get the PR reviewed and merged

**Comment by MarkEcza** [comment]
Binary of #78 - [link](https://github.com/YimMenu/HorseMenu/actions/runs/8239476315/artifacts/1318130751)

**Comment by Rxann** [comment]
> Binary of #78 - [link](https://github.com/YimMenu/HorseMenu/actions/runs/8239476315/artifacts/1318130751)

Thanks for doing this

**Comment by Hyman-R** [comment]
> > > @Hyman-R I have noticed there is a glitch when you resize the screen it may crash so I will be working to find a fix for that aswell
> > 
> > 
> > Get it, that's why I find the file has been deleted. Sure, wait for the updated version. Thanks!
> 
> I'm trying my best to get the PR reviewed and merged

Thank you and take your time.

**Comment by Hyman-R** [comment]
> Binary of #78 - [link](https://github.com/YimMenu/HorseMenu/actions/runs/8239476315/artifacts/1318130751)

Cool, let me have a try :)

**Comment by Hyman-R** [comment]
Seems like no lucky for me, still get crashed while injecting HorseMenu. The log is: 
[Error Log.txt](https://github.com/YimMenu/HorseMenu/files/14576260/Error.Log.txt)

Can help review it and see what I can do to resolve the issue? Thanks

**Comment by Rxann** [comment]
> Seems like no lucky for me, still get crashed while injecting HorseMenu. The log is: 
> 
> [Error Log.txt](https://github.com/YimMenu/HorseMenu/files/14576260/Error.Log.txt)
> 
> 
> 
> Can help review it and see what I can do to resolve the issue? Thanks

What OS are you using?

**Comment by Rxann** [comment]
> > Seems like no lucky for me, still get crashed while injecting HorseMenu. The log is: 
> > 
> > [Error Log.txt](https://github.com/YimMenu/HorseMenu/files/14576260/Error.Log.txt)
> > 
> > 
> > 
> > Can help review it and see what I can do to resolve the issue? Thanks
> 
> What OS are you using?

Also, at what point are you injecting the dll

**Comment by Hyman-R** [comment]
> > > Seems like no lucky for me, still get crashed while injecting HorseMenu. The log is:
> > > [Error Log.txt](https://github.com/YimMenu/HorseMenu/files/14576260/Error.Log.txt)
> > > Can help review it and see what I can do to resolve the issue? Thanks
> > 
> > 
> > What OS are you using?
> 
> Also, at what point are you injecting the dll

Thank you. The system is Windows 11 Professional 23H2. 64bit.  I've tried two points to inject: 1. In the main menu before going to RDR2 Online. 2.  After entering the RDR2 Online and standing on the ground.

**Comment by Hyman-R** [comment]
> > > > > Seems like no lucky for me, still get crashed while injecting HorseMenu. The log is:
> > 
> > 
> > > > > [Error Log.txt](https://github.com/YimMenu/HorseMenu/files/14576260/Error.Log.txt)
> > 
> > 
> > > > > Can help review it and see what I can do to resolve the issue? Thanks
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > What OS are you using?
> > 
> > 
> > > 
> > 
> > 
> > > Also, at what point are you injecting the dll
> > 
> > 
> > Thank you. The system is Windows 11 Professional 23H2. 64bit.  I've tried two points to inject: 1. In the main menu before going to RDR2 Online. 2.  After entering the RDR2 Online and standing on the ground.
> 
> Hmm, alright these are the points I use. What GPU do you use and are the drivers up to date? Outdated GPU drivers caused a crash for me too and once i updated it worked again.

It's AMD 6750 GRE and the driver is updated. I guess I have to give this dll up as it might be not compatible with my GPU...But...once you have the new build of the binary, please share it with me and I can have another try. Thank you.

**Comment by Rxann** [comment]
> > > > > > Seems like no lucky for me, still get crashed while injecting HorseMenu. The log is:
> 
> > > 
> 
> > > 
> 
> > > > > > [Error Log.txt](https://github.com/YimMenu/HorseMenu/files/14576260/Error.Log.txt)
> 
> > > 
> 
> > > 
> 
> > > > > > Can help review it and see what I can do to resolve the issue? Thanks
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > What OS are you using?
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Also, at what point are you injecting the dll
> 
> > > 
> 
> > > 
> 
> > > Thank you. The system is Windows 11 Professional 23H2. 64bit.  I've tried two points to inject: 1. In the main menu before going to RDR2 Online. 2.  After entering the RDR2 Online and standing on the ground.
> 
> > 
> 
> > Hmm, alright these are the points I use. What GPU do you use and are the drivers up to date? Outdated GPU drivers caused a crash for me too and once i updated it worked again.
> 
> 
> 
> It's AMD 6750 GRE and the driver is updated. I guess I have to give this dll up as it might be not compatible with my GPU...But...once you have the new build of the binary, please share it with me and I can have another try. Thank you.

You could try to build the binary yourself and use it. I will try to look at the log a little bit more in depth but I am in class right now so it will be later.

**Comment by DayibBaba** [comment]
This repo has lost my attention due to disinterest. Nurture your expectations regarding any updates or reviews. With that being said, in no way is this "menu" in a usable or user friendly state. So crashes are unavoidable with it.

**Comment by Rxann** [comment]
> This repo has lost my attention due to disinterest. Nurture your expectations regarding any updates or reviews. With that being said, in no way is this "menu" in a usable or user friendly state. So crashes are unavoidable with it.

I have fixed all of the known issues in my PR. At least the known issues that I have faced.

**Comment by Rxann** [comment]
> This repo has lost my attention due to disinterest. Nurture your expectations regarding any updates or reviews. With that being said, in no way is this "menu" in a usable or user friendly state. So crashes are unavoidable with it.

Furthermore, I would be happy to review PRs and such if there are not a lot of people that are available to do it.

**Comment by Rxann** [comment]
>  
> 
> > You could try to build the binary yourself and use it. I will try to look at the log a little bit more in depth but I am in class right now so it will be later.
> 
> 
> 
> Thank you. I don't know coding at all...

You do not need to code.

**Comment by wasguckstdu326** [comment]
Menu Crash after inject...

**Comment by Rxann** [comment]
> Menu Crash after inject...

That is what this fixes. Are you talking about the version with the fix or just the normal version?

**Comment by Rxann** [comment]
> Yea, do you got a new link from the menu, that i can Copy into the inject 

In #78 scroll up and download binary.zip that's linked from the bot. inject that.

**Comment by Hyman-R** [comment]
how to build it by myself?

**Comment by wasguckstdu326** [comment]
> > Yea, do you got a new link from the menu, that i can Copy into the inject
> 
> In #78 scroll up and download binary.zip that's linked from the bot. inject that.

thanks, but it still crash for me idk why ...

**Comment by Rxann** [comment]
> > > Yea, do you got a new link from the menu, that i can Copy into the inject
> 
> > 
> 
> > In #78 scroll up and download binary.zip that's linked from the bot. inject that.
> 
> 
> 
> thanks, but it still crash for me idk why ...
> 
> 

What are your pc specs? Are your drivers updated? Please send the log aswell.

**Comment by Rxann** [comment]
> how to build it by myself?

You should download visual studio and get msvc. you will also need cmake which you can probably install through visual studio also. then go into the directory, make a new folder called build. cd into build and run `cmake ..` . then run `cmake --build . --config Debug`You can swap Debug for Release if you want a faster more optimized binary. If you could provide a log with debug mode enabled that would be better because it tells you which line it went wrong on.

**Comment by Hyman-R** [comment]
> > how to build it by myself?
> 
> You should download visual studio and get msvc. you will also need cmake which you can probably install through visual studio also. then go into the directory, make a new folder called build. cd into build and run `cmake ..` . then run `cmake --build . --config Debug`You can swap Debug for Release if you want a faster more optimized binary. If you could provide a log with debug mode enabled that would be better because it tells you which line it went wrong on.

Thanks. I managed to build my version but still can't make it work. It does not crash, just can't work. Here is the log for further look if you could.
[log.txt](https://github.com/YimMenu/HorseMenu/files/14622637/log.txt)

**Comment by Rxann** [comment]
> > > how to build it by myself?
> > 
> > 
> > You should download visual studio and get msvc. you will also need cmake which you can probably install through visual studio also. then go into the directory, make a new folder called build. cd into build and run `cmake ..` . then run `cmake --build . --config Debug`You can swap Debug for Release if you want a faster more optimized binary. If you could provide a log with debug mode enabled that would be better because it tells you which line it went wrong on.
> 
> Thanks. I managed to build my version but still can't make it work. It does not crash, just can't work. Here is the log for further look if you could. [log.txt](https://github.com/YimMenu/HorseMenu/files/14622637/log.txt)

Okay, I have traced the issue to the hooking on Vulkan::AcquireNextImage2KHR. It is not able to hook the function and that is what is causing the error. I will work on a fix, but because I cannot replicate it this means that I don't really have an environment to test it on. The place the error is being caused seems to be in `core/hooking/DetourHook.hpp` `line 45`

**Comment by Rxann** [comment]
@Hyman-R due to me having the nvidia drivers and it working, I dont think it is a code problem. I think you may need to reinstall your drivers. [Link to reddit post with similar issue](https://www.reddit.com/r/vulkan/comments/98wp1m/vkacquirenextimagekhr_fails_by_throwing_an/) I think there should be some tutorials online. This is my best guess to what the problem is.
