### ISSUE TITLE
Game update - Signatures out of date

### ISSUE THREAD

**Issue by tyackman** [YimMenu/HorseMenu#86]
VMDetectionCallback & RequestControl have changed

**Comment by Rxann** [comment]
I have found the new RequestControl and vmcallback.
i will send them in a bit if they work

**Comment by Rxann** [comment]
@tyackman 
Could you check these? The game runs fine and everything but I want to make sure before I open a pr. I have it drafted and everything.

vmDetectionCallback:  `E8 ?? ?? ?? ?? 48 8B 0D ?? ?? ?? ?? 84 C0 0F 45 DF`
RequestControl: `48 8D 4C 24 40 E8 ?? ?? ?? ?? 48 83 C4 30`

**Comment by Rxann** [comment]
> > @tyackman 
> > 
> > Could you check these? The game runs fine and everything but I want to make sure before I open a pr. I have it drafted and everything.
> > 
> > 
> > 
> > vmDetectionCallback:  `E8 ?? ?? ?? ?? 48 8B 0D ?? ?? ?? ?? 84 C0 0F 45 DF`
> > 
> > RequestControl: `48 8D 4C 24 40 E8 ?? ?? ?? ?? 48 83 C4 30`
> 
> Not home atm. Sig them at the same place and make sure to account for any differences in the pointer arithmetic.

alright i think there may be an error in the vmcallback math.

**Comment by Rxann** [comment]
close this
