### ISSUE TITLE
[Request] XP Roles Multpilier

### ISSUE THREAD

**Issue by bunnybuddy213** [YimMenu/HorseMenu#90]
I think a good way to set yourself apart from the free mod menus and do it before the others would be to make this XP multiplier for roles such as bounty hunter and all the others

**Comment by bunnybuddy213** [comment]
Got it, if I found something I'll let you know

**Comment by Rxann** [comment]
> Got it, if I found something I'll let you know

it will probably involve patching a byte in a function to keep giving xp. could also involve hooking a function and then calling it in a loop, returning the original every time in the loop.

**Comment by Deadlineem** [comment]
I vote yes on this, Im trying to get my hunting wagon lmao
