### ISSUE TITLE
[Request] Auto Teleport On Waypoint

### ISSUE THREAD

**Issue by bunnybuddy213** [YimMenu/HorseMenu#91]
One feature very pratical

**Comment by Deadlineem** [comment]
> I will make this feature today, will have a pr open by tonight EST time.

While youre on the teleport subject, i was trying to work out a way to make a teleport to objective option.

There is a native MAP::TRACK_BLIP_GPS(Blip, hash) ON RDR2MODS native db that i didnt see in horsemenus natives, apparently, you put the blip id/hash and it automatically sets a waypoint to the blip?

![Screenshot_20240321-194759](https://github.com/YimMenu/HorseMenu/assets/24372625/a1fcafd6-ea95-4c53-94d7-9a8a8fbd7b2a)

**Comment by Deadlineem** [comment]
> I will make this feature today, will have a pr open by tonight EST time.

This should do the trick for auto teleporting to waypoint though, may need some tweaks

```
#include "core/commands/Command.hpp"
#include "game/features/Features.hpp"
#include "game/rdr/Natives.hpp"
#include "game/backend/ScriptMgr.hpp"
#include "util/teleport.hpp"
#include "core/frontend/Notifications.hpp"
#include <thread> // for std::this_thread
#include <chrono> // for std::chrono

namespace YimMenu::Features
{
    class AutoTpToWaypoint : public Command
    {
    private:
        bool isActive;

    public:
        AutoTpToWaypoint() : Command("autotptowaypoint", "Auto Teleport To Waypoint", "Toggle auto teleport to waypoint"), isActive(false) {}

        virtual void OnCall() override
        {
            isActive = !isActive;
            if (isActive) {
                Notifications::Show("Auto Waypoint Teleport", "Auto teleport to waypoint is now active", NotificationType::Info);
                // Start the loop in a separate thread
                std::thread loopThread(&AutoTpToWaypoint::Loop, this);
                loopThread.detach(); // Detach the thread to run in the background
            } else {
                Notifications::Show("Auto Waypoint Teleport", "Auto teleport to waypoint is now inactive", NotificationType::Info);
            }
        }

        void Loop() {
            while (isActive) {
                std::this_thread::sleep_for(std::chrono::seconds(1)); // Adjust the loop delay as needed
                if (MAP::IS_WAYPOINT_ACTIVE()) {
                    auto waypointCoords = YimMenu::Teleport::GetWaypointCoords();
                    YimMenu::Teleport::TeleportEntity(Self::PlayerPed, {waypointCoords.x, waypointCoords.y, 0.0f}, true);
                }
            }
        }
    };

    static AutoTpToWaypoint _AutoTpToWaypoint;
}
```

**Comment by Rxann** [comment]
> > I will make this feature today, will have a pr open by tonight EST time.
> 
> 
> 
> This should do the trick for auto teleporting to waypoint though, may need some tweaks
> 
> 
> 
> ```
> 
> #include "core/commands/Command.hpp"
> 
> #include "game/features/Features.hpp"
> 
> #include "game/rdr/Natives.hpp"
> 
> #include "game/backend/ScriptMgr.hpp"
> 
> #include "util/teleport.hpp"
> 
> #include "core/frontend/Notifications.hpp"
> 
> #include <thread> // for std::this_thread
> 
> #include <chrono> // for std::chrono
> 
> 
> 
> namespace YimMenu::Features
> 
> {
> 
>     class AutoTpToWaypoint : public Command
> 
>     {
> 
>     private:
> 
>         bool isActive;
> 
> 
> 
>     public:
> 
>         AutoTpToWaypoint() : Command("autotptowaypoint", "Auto Teleport To Waypoint", "Toggle auto teleport to waypoint"), isActive(false) {}
> 
> 
> 
>         virtual void OnCall() override
> 
>         {
> 
>             isActive = !isActive;
> 
>             if (isActive) {
> 
>                 Notifications::Show("Auto Waypoint Teleport", "Auto teleport to waypoint is now active", NotificationType::Info);
> 
>                 // Start the loop in a separate thread
> 
>                 std::thread loopThread(&AutoTpToWaypoint::Loop, this);
> 
>                 loopThread.detach(); // Detach the thread to run in the background
> 
>             } else {
> 
>                 Notifications::Show("Auto Waypoint Teleport", "Auto teleport to waypoint is now inactive", NotificationType::Info);
> 
>             }
> 
>         }
> 
> 
> 
>         void Loop() {
> 
>             while (isActive) {
> 
>                 std::this_thread::sleep_for(std::chrono::seconds(1)); // Adjust the loop delay as needed
> 
>                 if (MAP::IS_WAYPOINT_ACTIVE()) {
> 
>                     auto waypointCoords = YimMenu::Teleport::GetWaypointCoords();
> 
>                     YimMenu::Teleport::TeleportEntity(Self::PlayerPed, {waypointCoords.x, waypointCoords.y, 0.0f}, true);
> 
>                 }
> 
>             }
> 
>         }
> 
>     };
> 
> 
> 
>     static AutoTpToWaypoint _AutoTpToWaypoint;
> 
> }
> 
> ```

I have this feature in a looped command actually and it just checks it there is a waypoint and then runs a function to teleport. I will def submit my pr today though
