### ISSUE TITLE
Help with compile

### ISSUE THREAD

**Issue by drew52803** [YimMenu/HorseMenu#92]
Heyo kinda new to this, but it keeps giving me cmake generation failed when I try to build it. Is there any way I could get some help or sent it on discord by chance? add me if possible - moosetg          tysm!!

**Comment by Rxann** [comment]
> Heyo kinda new to this, but it keeps giving me cmake generation failed when I try to build it. Is there any way I could get some help or sent it on discord by chance? add me if possible - moosetg          tysm!!

is this resolved?
