### ISSUE TITLE
[Feature] Changing Weather

### ISSUE THREAD

**Issue by Deadlineem** [YimMenu/HorseMenu#99]
The first index value is the weather type, this is currently sunny.  I tried making a dropdown for it, didnt work out lol

Considered making a new tab under Self called World for this and under the world tab, columns for various things sort of like YimMenu.

ClearWeather.cpp
```#include "core/commands/Command.hpp"
#include "game/features/Features.hpp"
#include "game/rdr/Enums.hpp"
#include "game/rdr/Natives.hpp"
#include "core/frontend/Notifications.hpp"

namespace YimMenu::Features
{
	class ClearWeather : public Command
	{
		using Command::Command;

		virtual void OnCall() override
		{
			MISC::SET_WEATHER_TYPE(0x614A1F91, 0, 1, 1, 50.0, 0);
			MISC::_SET_OVERRIDE_WEATHER(0x614A1F91);
			Notifications::Show("Weather", "Weather has been set to Sunny.", NotificationType::Warning);
		}
	};

	static ClearWeather _ClearWeather{"clearweather", "Sunny Skies", "Changes the weather to Sunny."};
}

**Comment by Rxann** [comment]
I am going to implement train features at some point so i will make the world tab then.

**Comment by theofficialhackclean** [comment]
I already added weather option.

**Comment by Deadlineem** [comment]
> @Rxann I already added weather option with a world tab.

I have also done the same, Im currently working on a ped spawner to spawn in legendary animals.  Shall i post it here as well @Rxann ?

**Comment by Rxann** [comment]
> @Rxann I already added weather option with a world tab.

ah okay, when your pr gets merged that will work then.

**Comment by Rxann** [comment]
> > @Rxann I already added weather option with a world tab.
> 
> I have also done the same, Im currently working on a ped spawner to spawn in legendary animals. Shall i post it here as well @Rxann ?

I mean, I have already included some legendary animals in the ped spawner. You will need to change the outfits of models to get the legendary variant.

**Comment by Deadlineem** [comment]
> > > @Rxann I already added weather option with a world tab.
> > 
> > 
> > I have also done the same, Im currently working on a ped spawner to spawn in legendary animals. Shall i post it here as well @Rxann ?
> 
> I mean, I have already included some legendary animals in the ped spawner. You will need to change the outfits of models to get the legendary variant.

PedSpawner.cpp

```namespace YimMenu
{
	extern bool SpawnPed(std::string model_name, int player_ped_id, int outfit_preset);
}```

index 3 is the outfit for the ped you are spawning (Legendary boar is 1 while Legendary Alligator is 4) in the script ive been working on for testing, if you spawn them without an outfit, they will be invisible.

**Comment by Deadlineem** [comment]
Also @Rxann you need to fix the wagon spawner, it spawns the wagon behind you instead of in front (in the code the Y value

ENTITY::GET_OFFSET_FROM_ENTITY_IN_WORLD_COORDS(player_ped_id, 0.0, -10.0, 0.0);

change the -10.0 to 10.0 and that will spawn vehicles/peds/etc. in front of you.
